services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tds
      POSTGRES_USER: tds
      POSTGRES_PASSWORD: tds123
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tds"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tds
      SPRING_DATASOURCE_USERNAME: tds
      SPRING_DATASOURCE_PASSWORD: tds123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: